sudo: required
dist: precise
language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools

env:
  matrix:
    - API=android-21 ABI=armeabi-v7a
    # - API=android-22 ABI=armeabi-v7a
    # - API=android-23 ABI=armeabi-v7a
    # - API=android-24 ABI=armeabi-v7a
    # - API=android-25 ABI=armeabi-v7a
    # - API=android-26 ABI=armeabi-v7a
    # - API=android-27 ABI=armeabi-v7a
    - API=android-28 ABI=armeabi-v7a

# Emulator Management: Create, Start and Wait
before_script:
  - android-update-sdk --components=sys-img-$ABI-$API --accept-licenses='android-sdk-license-[0-9a-f]{8}'
  - echo no | android create avd --force -n test -t $API --abi $ABI
  - emulator -avd test -no-audio -no-window
  - android-wait-for-emulator &
  - adb shell input keyevent 82 &

script:
- ./gradlew clean assemble
